version: 2.1

machine:

 services:

  - docker

defaults: &defaults

 working_directory: "~/project"

 docker:

  - image: docker.artifactory.foc.zone/continuous-quality/provar:latest

 

enterprise_setup_step: &enterprise_setup_step

 run:

  name: "Prepare Enterprise Setup"

  command: "curl -sL https://tools.circleci.foc.zone/install-certs | bash -"

 

attach_workspace_step: &attach_workspace_step

 attach_workspace:

  at: "."

persist_workspace_step: &persist_workspace_step

 persist_to_workspace:

  root: "."

  paths: ["."]

 

env_var: &env_var

 WORKSPACE: ui_testing

 PROVAR_HOME: /srv/Provar/Provar_ANT_latest

 TESTRESULTS: ui_testing/ANT/Results

 

provar_test_run: &provar_test_run

 <<: *defaults

 steps:

  - *enterprise_setup_step

  - checkout

  - run:

    name: set provar secrets

    command: |

     pwd

     sed -i "s/provarClientId/${provarClientId}/g" ${WORKSPACE}/.secrets

     sed -i "s/provarClientSecret/${provarClientSecret}/g" ${WORKSPACE}/.secrets

     sed -i "s/provarRefreshToken/${provarRefreshToken}/g" ${WORKSPACE}/.secrets

     sed -i "s/provarAccessToken/${provarAccessToken}/g" ${WORKSPACE}/.secrets

     sed -i "s/saucelabAccessToken/${saucelabAccessToken}/g" ${WORKSPACE}/.secrets

  - run:

    name: Run UI Tests

    command: |

     xvfb-run --auto-servernum --server-args "-screen 0 1600x900x24" ant -f ${WORKSPACE}/ANT/${BUILD_FILENAME}.xml -v

  - store_artifacts:

    path: ui_testing/ANT/Results

  - store_test_results:

    path: ui_testing/ANT/Results/JUnit.xml
